# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Describe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200)),
            ],
        ),
    ]
