# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_describe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Describe',
        ),
        migrations.AddField(
            model_name='img',
            name='des',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
