# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170102_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='tit',
            field=models.CharField(default=1212, max_length=30),
            preserve_default=False,
        ),
    ]
