# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_img_tit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='room',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
