# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170105_0746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
