# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170106_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.IMG'),
        ),
    ]
