# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170106_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='context',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
        migrations.AddField(
            model_name='contact',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
