# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170106_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='auther',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='post_id',
            field=models.CharField(max_length=50),
        ),
    ]
